### ISSUE TITLE
Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by pfulton** [sparkbox/ember-cli-grunticon#1]
Hi folks,

I'm getting an error when trying to run `ember server` right after install.

```
Cannot read property 'options' of undefined
TypeError: Cannot read property 'options' of undefined
    at Class.module.exports.config (/node_modules/ember-cli-grunticon/index.js:13:19)
    at /node_modules/ember-cli/lib/models/project.js:204:27
    at Array.reduce (native)
    at Project.getAddonsConfig (/node_modules/ember-cli/lib/models/project.js:202:22)
    at Project.config (/node_modules/ember-cli/lib/models/project.js:180:29)
    at Class.<anonymous> (/node_modules/ember-cli/lib/commands/serve.js:44:31)
    at lib$rsvp$$internal$$tryCatch (/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

My `ember-cli-build.js` is set up as suggested in the docs:

```
grunticon: {
      src: "grunticon/src/+(*.svg|*.png)",
      dest: 'public/grunticon'
    }
```

I could simply be missing something on my end, as this is my first attempt at using Ember. Any help is appreciated! Thanks.

**Comment by cromwellryan** [comment]
Oh my! Totally missed this Issue! I'll take a look tomorrow...

**Comment by thoresuenert** [comment]
Still a thing. 
Will this issue be fixed in the near future?

**Comment by thoresuenert** [comment]
@pfulton if you still need a working version for grunticon:
https://github.com/thoresuenert/ember-grunticon
i did this today
